name: SpecialGround
main: EmreTr1\Main
version: 1.0
api: 3.0.0-ALPHA10
author: EmreTr1
description: SpecialGround Plugin for PocketMine
website: minedogs.tk
commands:
 spg:
   description: SpecialGround Plugin main Command
